server.port=3000
spring.application.name=api-empleados

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

# gRPC (puerto separado porque comparte HTTP/2 con REST es complejo)
grpc.server.port=9090

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html