services:
  api:
    build: .
    ports:
      - "3003:3000"   # <-- Cambiado de 3000:3000 a 3003:3000
    environment:
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB: practica3
      PORT: 3000
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    volumes:
      - datos:/data/db

volumes:
  datos: